apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
    - port: {{ .Values.services.frontend.port }}
      targetPort: {{ .Values.services.frontend.port }}
  selector:
    app: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.services.frontend.replicas }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.services.frontend.image | quote }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.services.frontend.port }}
          env:
            - name: BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: shopflow-config
                  key: BACKEND_URL
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.services.frontend.port }}
            initialDelaySeconds: 15
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.services.frontend.port }}
            initialDelaySeconds: 15
            periodSeconds: 15
