server.port=8081
spring.application.name=auth-service

# PostgreSQL Connection
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:127.0.0.1}:${POSTGRES_PORT:5432}/${POSTGRES_DB:ShopFlow}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:1234}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# JWT Config
jwt.secret=ShopFlowSuperSecretKey2024XYZABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghij
jwt.expiration=86400000
