apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
    - port: {{ .Values.services.inventoryService.port }}
      targetPort: {{ .Values.services.inventoryService.port }}
  selector:
    app: inventory-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.services.inventoryService.replicas }}
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service
          image: {{ .Values.services.inventoryService.image | quote }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.services.inventoryService.port }}
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: shopflow-config
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: shopflow-config
                  key: POSTGRES_PORT
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: shopflow-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: shopflow-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: shopflow-secrets
                  key: POSTGRES_PASSWORD
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: shopflow-config
                  key: KAFKA_BOOTSTRAP_SERVERS
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{ .Values.services.inventoryService.port }}
            initialDelaySeconds: 45
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: {{ .Values.services.inventoryService.port }}
            initialDelaySeconds: 45
            periodSeconds: 15
