apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
    - port: {{ .Values.services.notificationService.port }}
      targetPort: {{ .Values.services.notificationService.port }}
  selector:
    app: notification-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.services.notificationService.replicas }}
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: {{ .Values.services.notificationService.image | quote }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.services.notificationService.port }}
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: shopflow-config
                  key: KAFKA_BOOTSTRAP_SERVERS
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{ .Values.services.notificationService.port }}
            initialDelaySeconds: 45
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: {{ .Values.services.notificationService.port }}
            initialDelaySeconds: 45
            periodSeconds: 15
