server.port=8082
spring.application.name=product-catalog-service

# PostgreSQL Connection (Electronics)
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/ShopFlow
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# MongoDB Connection (Fashion)
spring.data.mongodb.uri=mongodb://127.0.0.1:27017/shopflow
spring.data.mongodb.database=shopflow

# JWT Config
jwt.secret=ShopFlowSuperSecretKey2024XYZABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghij
jwt.expiration=86400000
