apiVersion: v1
kind: ConfigMap
metadata:
  name: shopflow-config
  namespace: shopflow
data:
  # Database Connections
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "ShopFlow"
  POSTGRES_USER: "postgres"
  
  MONGO_HOST: "mongo"
  MONGO_PORT: "27017"
  MONGO_DB: "shopflow"
  
  ELASTICSEARCH_HOST: "elasticsearch"
  ELASTICSEARCH_PORT: "9200"
  
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  CACHE_TYPE: "redis"
  
  # Kafka Configs
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  
  # Service Discovery Hosts (internal K8s DNS)
  AUTH_SERVICE_HOST: "auth-service"
  PRODUCT_SERVICE_HOST: "product-catalog-service"
  CART_SERVICE_HOST: "cart-order-service"
  
  # Frontend Configs
  BACKEND_URL: "http://api-gateway:8080"
