apiVersion: v1
kind: Secret
metadata:
  name: shopflow-secrets
  namespace: shopflow
type: Opaque
data:
  # Base64 encoded values
  POSTGRES_PASSWORD: "MTIzNA==" # "1234"
  JWT_SECRET: "U2hvcEZsb3dTdXBlclNlY3JldEtleTIwMjRYWVpBQkNERUZHSElKS0xNTk9QUVJTVFVWV1hYWlphYmNkZWZnaGlq"
