apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: shopflow
spec:
  ports:
    - port: 8085
      targetPort: 8085
  selector:
    app: notification-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: shopflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: shopflow/notification-service:latest
          ports:
            - containerPort: 8085
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: shopflow-config
                  key: KAFKA_BOOTSTRAP_SERVERS
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8085
            initialDelaySeconds: 45
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8085
            initialDelaySeconds: 45
            periodSeconds: 15
